<?php
  if ($_REQUEST['scene']) {
    header("Location: index.php?scene=".$_REQUEST['scene']);
    die('<a href="index.php?scene='.$_REQUEST['scene'].'">Start</a>');
  }
?>
<html>
<head>
  <title>Gloomhaven Scenario Viewer - Choose Scene</title>
</head>

<body>
  <p class="header">Gloomhaven Scenario Viewer - Choose Scene</p>
  
  <div class="list">
    <ul>
<?php

  $locations = file("locations.txt");
  foreach ($locations as $line) {
    $line = trim($line);
    if (preg_match('/^\%\s(\d\d\d)\s(.*)$/', $line, $m)) {
      $num = $m[1];
      $txt = htmlentities($m[2]);
      print '<li><a href="index.php?scene='.$num.'">'.$num.': '.$txt.'</a></li>'."\n";
    }
  }
    
?>  
    </ul>
  </div>

<div class="footer">
Generated by <a href="https://github.com/dieck/GloomhavenScenarioViewer">GloomhavenScenarioViewer</a>.
<font size="-3">
Available on <a href="https://github.com/dieck/GloomhavenScenarioViewer">GitHub</a>, licensed unter <a href="license.php">AGPL-3.0</a>.
Images of Gloomhaven Scenarios are not part of the Viewer, and are supplied by the user using the tool. Authors of the Viewer tool are not responsible for possible copyright infringements.
</font>
</div>

</body>
</html>
